services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supply_chain_threat_backend
    ports:
      - "8080:8080"
    command: ["python", "backend_api.py"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supply_chain_threat_frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
