version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supply_chain_threat_backend
    ports:
      - "8080:8080"
    volumes:
      - ./models:/app/models   # Mount models folder into container
    command: ["python", "backend_api.py"]
