version: '3.9'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    command: uvicorn backend_api:app --host 0.0.0.0 --port 8080
    volumes:
      - .:/app

  frontend:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run streamlit_app.py --server.port 8501
    volumes:
      - .:/app
    depends_on:
      - backend