version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supply_chain_threat_backend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: always
    command: ["python", "backend_api.py"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supply_chain_threat_frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    restart: always
    command: ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
